default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'passwd' %>
  port: <%= ENV['DB_PORT'] || 3306 %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: rails7_todo_development

test:
  <<: *default
  database: rails7_todo_test

production:
  <<: *default
  database: rails7_todo_production
